### PR TITLE
RFC to deprecate some older buildpack and platform APIs

### PR DESCRIPTION
**Pull request by natalieparellano**
[Readable](https://github.com/buildpacks/rfcs/blob/deprecate-apis/text/0000-deprecate-apis.md)

### CODE REVIEW

**Review by jabrown85 — APPROVED** [review]
Love to see this being discussed.

**Comment by natalieparellano** [comment]
I'd like to "call for votes" on this one, as it seems we are generally in favor of it. Adding the FCP label closing next Wednesday 8/31 (to give time for 2 Team Lead syncs).

**Comment by natalieparellano** [comment]
Moving this to "voting" with close date of next Friday 11/11

**Review by samj1912 — APPROVED** [review]

**Review by dmikusa — APPROVED** [review]

**Review by jkutner — APPROVED** [review]

**Review by AidanDelaney — APPROVED** [review]
LGTM

**Pull request merged**
