### PR TITLE
RFC for renaming launch.toml

### PR DESCRIPTION
**Pull request by hone**
[rendered](https://github.com/hone/cnb-rfcs/blob/rename-app-toml/text/0000-rename-app-toml.md)

Let the bikeshed commence!

### CODE REVIEW

**Comment by jkutner** [comment]
Is it possible that `project.toml` (with the same name and schema) becomes the app descriptor that was roughly described in #3? If yes, we should consider that when deciding on the name (even though it may not change anything).

**Comment by hone** [comment]
@jkutner I'm fine with that. I'm not strongly opinionated on the filename itself, but we should move away from `app.toml` in the spec since there are no plans to make that change.

**Comment by sclevine** [comment]
@nebhale Note that we voted in the WG meeting to revert the spec commit changing `launch.toml` to `app.toml`, given that there was never an RFC for it and it was never implemented in the lifecycle. This RFC is now about renaming `launch.toml` to something else.

@hone changing the title accordingly, hope you don't mind 😄

**Comment by hone** [comment]
@sclevine yeah, no worries.
@nebhale I'm fine with that. Did you have new work in mind?

Should we just close/merge this in?

**Pull request closed without merging**
